SELECT * FROM dbamv.SOLICITACAO_OS ;

SELECT * FROM ALL_TAB_COLUMNS atc WHERE atc.COLUMN_NAME = 'CD_OS';
SELECT * FROM ALL_TAB_COLUMNS atc WHERE atc.COLUMN_NAME = 'CD_FUNC';
SELECT faux.CD_FUNC FROM dbamv.FUNCIONARIO faux WHERE faux.CD_USUARIO = '000001386200'; 

--UPDATE
SELECT *
FROM dbamv.SOLICITACAO_OS sol
WHERE sol.CD_OFICINA = 9
AND sol.CD_MULTI_EMPRESA = 1
AND sol.CD_OS IN (856666, 856743)
ORDER BY sol.DT_PEDIDO DESC;

UPDATE dbamv.SOLICITACAO_OS so
SET 
  so.DT_EXECUCAO = SYSDATE + INTERVAL '5' MINUTE,
  so.TP_SITUACAO = 'C',
  so.CD_ESPEC = 43,
  so.DT_ULTIMA_ATUALIZACAO = SYSDATE + INTERVAL '10' MINUTE,
  so.TP_LOCAL = 'I',
  so.CD_MOT_SERV = 54,
  so.SN_RECEBIDA = 'S',
  so.CD_RESPONSAVEL = '000001386200', --TEM QUE SER O MOTORISTA DA SAIDA
  so.CD_USUARIO_RECEBE_SOL_SERV = '000001386200', --TEM QUE SER O MOTORISTA DA SAIDA, 
  so.DT_USUARIO_RECEBE_SOL_SERV = SYSDATE + INTERVAL '5' MINUTE,
  so.CD_USUARIO_FECHA_OS = '000001386200', --TEM QUE SER O MOTORISTA DA SAIDA, 
  so.DT_USUARIO_FECHA_OS = SYSDATE + INTERVAL '10' MINUTE
WHERE so.CD_OS = 856743;

  --INSERT
  SELECT *
  FROM dbamv.ITSOLICITACAO_OS itsol
  WHERE itsol.CD_OS IN (856666, 856743);

SELECT dbamv.SEQ_SOLICITACAO

INSERT INTO dbamv.ITSOLICITACAO_OS itsol
SELECT
  dbamv.SEQ_ITOS.NEXTVAL AS CD_ITSOLICITACAO_OS, 
  SYSDATE - INTERVAL '15' MINUTE AS HR_FINAL, 
  SYSDATE - INTERVAL '5' MINUTE AS HR_INICIO, 
  1 AS VL_TEMPO_GASTO, 
  856743 AS CD_OS, --TRAZER A OS DA SAIDA
  (SELECT faux.CD_FUNC FROM dbamv.FUNCIONARIO faux WHERE faux.CD_USUARIO = '000001386200') AS CD_FUNC, --TEM QUE SER O MOTORISTA DA SAIDA,
  11479 AS CD_SERVICO, 
  NULL AS DS_SERVICO, 
  10 AS VL_TEMPO_GASTO_MIN, 
  'S' AS SN_CHECK_LIST, 
  NULL AS VL_REAL, 
  NULL AS CD_BEM, 
  NULL AS VL_REFERENCIA, 
  NULL AS CD_LEITURA, 
  1 AS VL_HORA, 
  NULL AS VL_HORA_EXTRA, 
  NULL AS VL_EXTRA, 
  NULL AS VL_EXTRA_MIN, 
  NULL AS DS_FUNCIONARIO, 
  NULL AS CD_ITSOLICITACAO_OS_INTEGRA, 
  NULL AS CD_SEQ_INTEGRA, 
  NULL AS DT_INTEGRA, 
  NULL AS CD_ITSOLICITACAO_OS_FILHA, 
  NULL AS CD_TIPO_PROCEDIMENTO_PLANO
FROM DUAL;



SELECT * FROM portal_check_car.SAI_RET_VEICULO srv

SELECT cdaux.CD_OS_MV FROM portal_check_car.CHAMADOS_DESIGNADOS cdaux WHERE cdaux.CD_CHAMADO_DESIGNADO = 2
